// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkxubvlllllnesayakpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreHVidmxsbGxsbmVzYXlha3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTEyMTQsImV4cCI6MjA3MDY2NzIxNH0.zmonM8SJ6P988R9_jQsTMdq1nvKDiBh8uLgPi2VaXnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});